spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catelog
    username: postgres
    password: 271002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
  application:
    name: catalog-service